### PR TITLE
Water Shader Improvements

### PR DESCRIPTION
**Pull request by mtroyka**
-Reduces distortion of reflections and refractions.
-Adjusts the fresnel term to make reflections fall off more naturally.
-Fixes specular reflections for water.
-Increases the reflection and refraction texture sizes to screen size.

-Cleaned up a few things in WaterManager and Renderer.
-Cleaned up a bunch of things in the water shader.
-Tiny cleanup in the dof shader

# Housekeeping stuff
-Adjusted gitignore to account for visual studio.
-Added wxwidgets to gitignore.

-Added an include to one of the library source files to fix a compile issue. (in C11 you have to include stdint to get standard int types)

### CODE REVIEW

**Comment by mtroyka** [comment]
Something else I forgot: waves actually had a foam algo (normal waves not shore waves) but you've never seen it because it was set so that they were only visible from certain camera angles. Now foam caps are visible from all directions (mostly for ocean waves and depends on waviness).

**Comment by Psyringe** [comment]
I guess developers won't like changing the code conventions. Why not just stick to whatever it was? The feature is great btw.

**Comment by KieranP** [comment]
Hey @mtroyka . Thanks for your contribution. We don't actually manage contributions here, this is just a mirror. Please turn it into a patch and provide it here: http://trac.wildfiregames.com/  Thanks

**Comment by FabioPedretti** [comment]
@KieranP: can you disable submitting pull request here, to avoid contributor regularly try to to them?

**Comment by KieranP** [comment]
@FabioPedretti I don't believe github supports turning off pull requests. I've already disable github issues and wiki, but there is no function to disable pull requests. If you can find documentation that proves it can be done, I'll be quite happy to follow it, but I've searched and not found anything.

**Comment by FabioPedretti** [comment]
You are right, I found this, no idea how can be used however: https://nopullrequests.appspot.com

**Pull request closed without merging**
