### PR TITLE
Fix build with miniupnpc 2.2.8

### PR DESCRIPTION
**Pull request by emilazy**
See <https://github.com/miniupnp/miniupnp/blob/miniupnpc_2_2_8/miniupnpc/Changelog.txt>.

Yes, they really decided to add a return code in the middle of their existing range, changing the semantics, in a release that bumped the version number by 0.0.1…

I saw that your main repository is still on Subversion and that there’s also a Gitea instance being tested. I wasn’t sure what the best way to contribute this patch back upstream would be, so I hope it’s okay to send a pull request here! Feel free to reroute this wherever it needs to go.

### CODE REVIEW

**Comment by emilazy** [comment]
By the way, if you’d rather this match the other cases and continue through the rest of the logic I can do that; I just figured that a reserved IP would never give a useful result.

**Comment by StanleySweet** [comment]
Hey,
Thank you for your interest in contributing to 0 A.D!  You are correct we are still using Subversion and [Phabricator](https://code.wildfiregames.com) for contributions for now. So ideally you'd post your patch there if that's not too much trouble. You can create a diff using `git diff -x -U5000` and upload it through the webinterface there. Once I'll add you to the contributors we'll be able to run the CI on it.

If you're interested in the git migration feel free to contribute to the discussion on [the forums](https://wildfiregames.com/forum/topic/115363-a-new-git-based-development-environment/).

Regarding the patch itself it looks alright. Have you tested it ? Windows version currently is on 2.2.0 and macOS version is on 2.2.2. 

> By the way, if you’d rather this match the other cases and continue through the rest of the logic I can do that; I just figured that a reserved IP would never give a useful result.

It seems we let the code fail for any other broken cases so you might keep that consistent, yeah. I don't have a strong feeling about it. Might be interesting to test it both with and without the patch to see what happens.

You also need to add yourself to the credits, see [wiki:SubmittingPatches](https://trac.wildfiregames.com/wiki/SubmittingPatches)

**Comment by emilazy** [comment]
I’m afraid I didn’t do runtime testing; this was part of a [mass migration to miniupnpc 2.2.8](https://github.com/NixOS/nixpkgs/pull/325273) I handled over at NixOS and I tried to send every patch I wrote myself upstream. But maybe I should try the game! :)

For what it’s worth, other distros have also done this migration, and e.g. Arch is already shipping [a patch that doesn’t handle backwards compatibility or the renumbered return values](https://gitlab.archlinux.org/archlinux/packaging/packages/0ad/-/blob/41e5b7b44ded73f268a170f7989342a41242d0fd/miniupnpc-2.2.8.patch). The [miniupnpc commit](https://github.com/miniupnp/miniupnp/commit/c0a50ce33e3b99ce8a96fd43049bb5b53ffac62f) that broke things is quite simple, just adding two new optional parameters and an additional return code to provide some more nuance to a failure case, so I’m pretty confident that this change is correct given that it builds correctly. Whether other changes in 2.2.8 might have broken things, I can’t say; that’s something we’ll be finding out as an ecosystem soon.

I’ll try to find the time to get this moved over to Phabricator. (But I also don’t mind if someone just steals this to commit; the changes are so trivial as to be uncopyrightable anyway.)

**Comment by StanleySweet** [comment]
Merged. Thanks again!

**Pull request closed without merging**
